version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: django_app
    command: sh ./run_web.sh
    ports:
      - "8080:8080"
    links:
      - worker
      - broker

  broker:
    image: redis
    hostname: redis
    command: redis-server
    ports:
      - "6379:6379"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: celery
    command: sh ./run_celery.sh
    user: nobody
    depends_on:
      - broker

