# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-11 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0002_auto_20180711_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='user_email',
            field=models.EmailField(default='', max_length=200),
        ),
    ]
